# Backend configuration is provided at init time via:
#   terraform init -backend-config=../../../config/backend-prod.hcl
#
# The config file is generated by scripts/bootstrap-state.sh
# It is gitignored — contains account-specific values.
# Anyone cloning this repo must run bootstrap-state.sh first.

terraform {
  backend "s3" {}
}
