apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets
  annotations:
    # Updated automatically by scripts/generate-config.sh after terraform apply
    # Format: arn:aws:iam::{account-id}:role/{project}-{env}-eso-role
    eks.amazonaws.com/role-arn: arn:aws:iam::482352877891:role/petclinic-prod-eso-role
